version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db-mysql-******.db.ondigitalocean.com
      DB_USER: doadmin
      DB_PASSWORD: password**
      DB_PORT: 25060
      DB_DATABASE: defaultdb
      DB_SSLMODE: REQUIRED
     